// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: order_details.sql

package db

import (
	"context"
)

const createOrderDetails = `-- name: CreateOrderDetails :one
INSERT INTO order_details (order_pk, product_pk, quantity, price)
    VALUES ($1, $2, $3, $4)
RETURNING
    pk, order_pk, product_pk, quantity, price, discount, created_at, updated_at
`

type CreateOrderDetailsParams struct {
	OrderPk   int64 `json:"order_pk"`
	ProductPk int64 `json:"product_pk"`
	Quantity  int32 `json:"quantity"`
	Price     int32 `json:"price"`
}

func (q *Queries) CreateOrderDetails(ctx context.Context, arg CreateOrderDetailsParams) (OrderDetail, error) {
	row := q.db.QueryRow(ctx, createOrderDetails,
		arg.OrderPk,
		arg.ProductPk,
		arg.Quantity,
		arg.Price,
	)
	var i OrderDetail
	err := row.Scan(
		&i.Pk,
		&i.OrderPk,
		&i.ProductPk,
		&i.Quantity,
		&i.Price,
		&i.Discount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderDetails = `-- name: DeleteOrderDetails :exec
DELETE FROM order_details
WHERE pk = $1
`

func (q *Queries) DeleteOrderDetails(ctx context.Context, pk int64) error {
	_, err := q.db.Exec(ctx, deleteOrderDetails, pk)
	return err
}

const getOrderDetails = `-- name: GetOrderDetails :one
SELECT
    pk, order_pk, product_pk, quantity, price, discount, created_at, updated_at
FROM
    order_details
WHERE
    pk = $1
`

func (q *Queries) GetOrderDetails(ctx context.Context, pk int64) (OrderDetail, error) {
	row := q.db.QueryRow(ctx, getOrderDetails, pk)
	var i OrderDetail
	err := row.Scan(
		&i.Pk,
		&i.OrderPk,
		&i.ProductPk,
		&i.Quantity,
		&i.Price,
		&i.Discount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderDetailsByOrderPk = `-- name: GetOrderDetailsByOrderPk :many
SELECT
    pk, order_pk, product_pk, quantity, price, discount, created_at, updated_at
FROM
    order_details
WHERE
    order_pk = $1
`

func (q *Queries) GetOrderDetailsByOrderPk(ctx context.Context, orderPk int64) ([]OrderDetail, error) {
	rows, err := q.db.Query(ctx, getOrderDetailsByOrderPk, orderPk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderDetail
	for rows.Next() {
		var i OrderDetail
		if err := rows.Scan(
			&i.Pk,
			&i.OrderPk,
			&i.ProductPk,
			&i.Quantity,
			&i.Price,
			&i.Discount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderDetails = `-- name: UpdateOrderDetails :one
UPDATE
    order_details
SET
    order_pk = $2,
    product_pk = $3,
    quantity = $4,
    price = $5,
    discount = $6
WHERE
    pk = $1
RETURNING
    pk, order_pk, product_pk, quantity, price, discount, created_at, updated_at
`

type UpdateOrderDetailsParams struct {
	Pk        int64 `json:"pk"`
	OrderPk   int64 `json:"order_pk"`
	ProductPk int64 `json:"product_pk"`
	Quantity  int32 `json:"quantity"`
	Price     int32 `json:"price"`
	Discount  int32 `json:"discount"`
}

func (q *Queries) UpdateOrderDetails(ctx context.Context, arg UpdateOrderDetailsParams) (OrderDetail, error) {
	row := q.db.QueryRow(ctx, updateOrderDetails,
		arg.Pk,
		arg.OrderPk,
		arg.ProductPk,
		arg.Quantity,
		arg.Price,
		arg.Discount,
	)
	var i OrderDetail
	err := row.Scan(
		&i.Pk,
		&i.OrderPk,
		&i.ProductPk,
		&i.Quantity,
		&i.Price,
		&i.Discount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
